[package]
name = "cairo_erc_3525"
version = "2.0.2"

[lib]

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0-rc.0" }
cairo_erc_721 = { git = "https://github.com/carbonable-labs/cairo-erc-721" }

[[target.starknet-contract]]
sierre = true
casm = true

[tool.snforge]
exit_first = false